### ISSUE TITLE
Powershell doesn't execute install

### ISSUE THREAD

**Issue by Aramstoteles** [gregchak/plex-playlist-import#11]
So i tried running the "Install" file by run with powershell but it just opens and quickly closes. I have Windows 11. Is there something i'm doing wrong?

**Comment by sweiggster51** [comment]
type "Set-ExecutionPolicy Unrestricted -Scope CurrentUser" into powershell, though I am getting an error that the certificate has expired

**Comment by gregchak** [comment]
Release 1.1.1.0 is available and had updated cert
