### ISSUE TITLE
Install fails due to expired certificate

### ISSUE THREAD

**Issue by jamesmusik** [gregchak/plex-playlist-import#12]
Attempting to install gives the following message: "Error: The developer certificate "D:\Music\Playlists\PlexPlaylistImport_1.1.0.0\PlexPlaylistImport_1.1.0.0_x86_x64_Debug.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate."

**Comment by gregchak** [comment]
Release 1.1.1.0 is available and has updated cert

**Comment by jamesmusik** [comment]
Thanks for the quick response!

**Comment by gregchak** [comment]
The zip file for the install package was left off of the release.  The release has been updated to include the zip.  You can use that to install.  Sorry about that.
