### ISSUE TITLE
Cant Install Due to Expired Certificate 

### ISSUE THREAD

**Issue by MoSample** [gregchak/plex-playlist-import#13]
I'm not overly familiar with how all this works, but i cant get this to install. I could be doing something wrong but to me it seems the latest release doesn't have a way to install, I'm guessing its because you have only included the source code?

So i tried the previous version with the file [PlexPlaylistImport_1.1.0.0.zip] and i get this error when running with PowerShell

Error: The developer certificate "C:\Users\......\Desktop\PlexPlaylistImport_1.1.0.0\PlexPlaylistImport_1.1.0.0_x86_x64_Debug.cer" has expired. One possible cause is the system clock isn't set to the correct date and time. If the system settings are correct, contact the app owner to re-create a package or bundle with a valid certificate.

I get the same error running the other PowerShell file. Am I doing something wrong?
Thanks

**Comment by criticalfiction** [comment]
Is a release of 1.1.1 likely, or is the expectation that users will build locally from source?

**Comment by gregchak** [comment]
The zip file for the install package was left off of the release.  The release has been updated to include the zip.  You can use that to install.  Sorry about that.
