### ISSUE TITLE
New certificate version?

### ISSUE THREAD

**Issue by csjjpm** [gregchak/plex-playlist-import#15]
Hi,
is it possible to get a new certificate so that I can install?
Thank you
Paul

**Comment by gregchak** [comment]
New release published with updated certificate

**Comment by csjjpm** [comment]
Thank you, you are a gentleman and a scholar

**Comment by csjjpm** [comment]
.....any way I can script a batch file with multiple commands, hundreds!

**Comment by csjjpm** [comment]
I see someone else has requested this so I've added to that.

Great job
