### ISSUE TITLE
How do I make this work

### ISSUE THREAD

**Issue by morpheus5150** [gregchak/plex-playlist-import#3]
I came across this and would like to install but am not sure how to.  Do you have the built program so that I can use it?

**Comment by gregchak** [comment]
There a single release for this project labeled "Initial Build".  Under assets, download "PlexPlaylistImport_1.0.4.0.zip".  When you extract that you will see the `Install.ps1` powershell script. To install you need to run the powershell script `Install.ps1`. You may be asked to install a certificate during the installation process. This is a development/testing certificate.

**Comment by morpheus5150** [comment]
I was able to get it installed.  Weird thing is it only imported 46 songs out of 692 for my playlist.  Any ideas?
________________________________

**Comment by gregchak** [comment]
I haven't seen a partial import before.  Are all the 692 song already part of your music library?  I would confirm that and confirm the file paths to the ones that are missing.  Other than that, I'm not sure.  Whenever myself or others have imported it was all or nothing, meaning the entire playlist imported or it didn't. One thing I will mention is that I have not tried a playlist that large.  It shouldn't make a difference but at the same time I've not verified one of that size.

**Comment by morpheus5150** [comment]
Yeah they all have the same path and are in the library.  Sonos imports it fine.   So kinda weird.
________________________________

**Comment by gregchak** [comment]
I'll see if I can generate a large playlist and give it a try.  Have you tried deleting the playlist and trying again?  Does it always stop at 46 songs? Does it stop at the 46th song in the ordered playlist or does it add 46 songs randomly throughout the playlist?

**Comment by morpheus5150** [comment]
Yes.  46 songs towards the middle of playlist.  Same one though.
________________________________

**Comment by gregchak** [comment]
OK.  Same 46 songs.  So it starts at the same song in the playlist file and ends at the same song.   Would you be willing/able to provide me with the playlist file?  Are you uploading to a PMS on Windows/Mac/etc. or to a NAS like Synology, etc.?

**Comment by gregchak** [comment]
Have you tried other playlists?  Do they have the same 46 song limit?

**Comment by morpheus5150** [comment]
Sure this is the file.  It is on a windows machine

**Comment by morpheus5150** [comment]
OK I figured something out.  In the m3u it was not importing ones with \\MORPHEUS\<file://MORPHEUS/>

If I changed it to \\Morpheus\<file://Morpheus/> it worked

I am still getting only 578 out of 694 songs imported.  Attached is the playlist.  Can you see something else?

**Comment by morpheus5150** [comment]
OK I found the other one

\\Morpheus\music\Rise Against\Appeal To Reason\10-Hero of War.mp3<file://Morpheus/music/Rise%20Against/Appeal%20To%20Reason/10-Hero%20of%20War.mp3>

If I change to this it works

\\Morpheus\Music\Rise Against\Appeal To Reason\10-Hero of War.mp3<file://Morpheus/Music/Rise%20Against/Appeal%20To%20Reason/10-Hero%20of%20War.mp3>


The Music needs to be Title case.  Any ideas how to solve this?  Your program is awesome.  Also when closing and reopening program it does not save the entries(that is URL,Token and so on)

**Comment by gregchak** [comment]
Can you check the casing of the actual file name on disk?  Does it match the casing of what you changed to make it work?

**Comment by gregchak** [comment]
I'm actually surprised that its able to work at all by specifying a network path (`\\computer_name`).  Plex must have updated that.  Previously it needed to be an absolute path on PMS.  For instance, you mentioned you're running PMS on Windows.  So all of your file paths should have started with your drive letter, like `C:\Music\...`.

**Comment by morpheus5150** [comment]
The casing on the disk is \\MORPHEUS\Music<file://MORPHEUS/Music>
The casing in plex library is \\Morpheus\Music<file://Morpheus/Music>

The issue is that it really shouldn’t matter.  Not sure how to just push it through

**Comment by morpheus5150** [comment]
I’ve always used UNC names for library

So do you think you can find a way to workaround the different CASE issues?

**Comment by gregchak** [comment]
I'd have to look into what can be done about the casing.  This app doesn't actually create the playlists.  It leverages the exposed APIs that PLEX has to perform a playlist import. It takes all the information put in the form, packages it into a request and sends it to PLEX to process. So I can't necessarily check the casing of what's in the playlist file against what is on disk because I don't have access to view file information, especially if PMS is on a different computer.  Running the app and PMS on the same computer, it might be an option.  I'd have to look into it.  But it seems like the casing is something that PMS is enforcing/requiring the file path.

**Comment by morpheus5150** [comment]
That’s weird because when I use MusConv it will send it over to plex without modifying.  Well if you can work it out I’d like to send you some cash.  Your program is something I have been looking for some time now

**Comment by gregchak** [comment]
I hadn't heard of that app/service.  I'll give them a look.  I wonder if there are other APIs that PLEX exposes that can validate a file path.  There's no real authoritative documentation on their APIs that I've found.  

I'll post any updates here.  Also, if you wouldn't mind, I like your idea for saving the field values so they are repopulated when opening the app.  Would you mind adding that specific thing as an Issue?

**Comment by morpheus5150** [comment]
Sure.  I’ll go in there an add that issue.  Good job on this
________________________________

**Comment by morpheus5150** [comment]
I get the below and am not even able to transfer now

***@***.***

**Comment by morpheus5150** [comment]
Actually it worked but I do get that Object error

**Comment by morpheus5150** [comment]
How do I update to the latest build?  I dont see the install package just the project

**Comment by gregchak** [comment]
For some reason GitHub isn't allowing me to upload the zip file. I'll post
a reply to this issue when I'm able to get it uploaded.

**Comment by LamontG** [comment]
Is the powershell script still included in the assets folder? I did not see it and the zip I have is 1.1.0.0.

**Comment by gregchak** [comment]
When you extract the zip, in the root folder is a file named `Install.ps1`.  Run this file to install.

**Comment by LamontG** [comment]
I got it to work.

Thanks

Lamont Greene
(980) 300-1236
