### ISSUE TITLE
Save entries

### ISSUE THREAD

**Issue by morpheus5150** [gregchak/plex-playlist-import#4]
Could you make it where once you enter the fields (URL,Token,Section, and Path) they can be saved, then the next time it is open they are already populated.  Thanks

Sean

**Comment by gregchak** [comment]
Release 1.1.0.0 adds ability to save previously entered info and prepopulates it when the application is opened.

**Comment by gregchak** [comment]
You should be able to check the installed version by going to your start menu and 

1. typing in "Plex Playlist Import"
2. Clicking the arrow next to the found entry
3. Click on App Settings
4. This will open up a window that displays the application's version number

Start Menu:
![image](https://user-images.githubusercontent.com/5882933/168934663-8a908805-81ed-475d-a6d6-1d0333d770f8.png)
 
App Settings:
![image](https://user-images.githubusercontent.com/5882933/168934692-ad03c91e-119c-4562-bb20-c10854520c3b.png)

**Comment by gregchak** [comment]
Logs and the JSON used to load the form will be located here: (adjust for your username)
`C:\Users\{username}\AppData\Local\Packages\ChakFrost.PlexPlaylistImport_{letters and numbers}\LocalState\previousInput.json`
