### ISSUE TITLE
Install.ps1 fails with certificate expiration error

### ISSUE THREAD

**Issue by wilchak** [gregchak/plex-playlist-import#5]
Hello,

I am unable to get the app to install due to the expired certificate. I have tried importing it into Third Party Root Certificates, but there seems to be no way to get PowerShell to ignore the expiration date on the cert, regardless of whether the system thinks it is "trusted."

It appears a new certificate will need to be generated on your end.

Thanks.

**Comment by gregchak** [comment]
New release published.  Its called Updated Certificate

**Comment by wilchak** [comment]
It looks like the .cer file in this zip https://github.com/gregchak/plex-playlist-import/releases/download/1.0.4.0-cert-update/PlexPlaylistImport_1.0.4.0.zip is unchanged from the original release... unless I'm missing something. I am still getting a certificate expiration warning, and the cert dates are identical.

**Comment by gregchak** [comment]
I think I uploaded the wrong zip.  Give it another try now.

**Comment by wilchak** [comment]
Thanks, that worked.
