### ISSUE TITLE
Install.ps1 not found?

### ISSUE THREAD

**Issue by bradleyhet** [gregchak/plex-playlist-import#8]
Downloading the "plex-playlist-import-main.zip" but Intall.ps1 not found, any ideas? thanks.

**Comment by gregchak** [comment]
I'm not sure where you got that file.  Under Releases, expand the Assets under 1.1.0.0.  There should be a zip called "PlexPlaylistImport_1.1.0.0.zip".  That is the .zip you should download and it has the install.ps1 included in it.

**Comment by bradleyhet** [comment]
thanks for that, all good. 👍
